# Generated by Django 6.1 on 2026-10-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_conversation_options_remove_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
